export const PROFILE_KEY = 'ocwp_profile';
export const HISTORY_KEY = 'ocwp_history';
export const SETTINGS_KEY = 'ocwp_settings';

export const GOAL_OPTIONS = [
  'Lose Weight',
  'Build Muscle',
  'Improve Fitness',
  'Increase Strength',
  'Boost Endurance',
  'Stay Consistent'
];

export const GENDER_OPTIONS = [
  'Female',
  'Male',
  'Non-binary',
  'Prefer not to say'
];

export const OPENAI_MODELS = [
  'gpt-4o-mini',
  'gpt-4.1-mini',
  'gpt-4o'
];

export const DEFAULT_SETTINGS = {
  useOpenAI: false,
  openAIApiKey: '',
  openAIModel: OPENAI_MODELS[0]
};

export const LOCAL_EXERCISE_LIBRARY = [
  {
    name: 'Air Squats',
    category: 'strength',
    focuses: ['Full Body', 'Lower Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate', 'High'],
    impacts: ['low', 'moderate'],
    goals: ['Lose Weight', 'Improve Fitness', 'Increase Strength', 'Stay Consistent'],
  },
  {
    name: 'Tempo Squats',
    category: 'strength',
    focuses: ['Full Body', 'Lower Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['low', 'moderate'],
    goals: ['Build Muscle', 'Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Goblet Squats',
    category: 'strength',
    focuses: ['Full Body', 'Lower Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Dumbbells', 'Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low', 'moderate'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Split Squats',
    category: 'strength',
    focuses: ['Lower Body', 'Full Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight', 'Dumbbells'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Build Muscle', 'Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Reverse Lunges',
    category: 'strength',
    focuses: ['Lower Body', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight', 'Dumbbells'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Lose Weight', 'Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Step-Ups',
    category: 'strength',
    focuses: ['Lower Body', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight', 'Dumbbells'],
    intensity: ['Moderate'],
    impacts: ['low', 'moderate'],
    goals: ['Improve Fitness', 'Boost Endurance', 'Stay Consistent'],
  },
  {
    name: 'Glute Bridges',
    category: 'strength',
    focuses: ['Lower Body', 'Full Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight', 'Bands', 'Dumbbells'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength', 'Stay Consistent'],
  },
  {
    name: 'Romanian Deadlifts',
    category: 'strength',
    focuses: ['Lower Body', 'Full Body'],
    environments: ['Gym', 'Home'],
    equipment: ['Dumbbells', 'Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Band Lateral Walks',
    category: 'strength',
    focuses: ['Lower Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bands'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness', 'Build Muscle'],
  },
  {
    name: 'Calf Raises',
    category: 'strength',
    focuses: ['Lower Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight', 'Dumbbells'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness'],
  },
  {
    name: 'Push-Ups',
    category: 'strength',
    focuses: ['Upper Body', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Build Muscle', 'Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Incline Push-Ups',
    category: 'strength',
    focuses: ['Upper Body', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness', 'Build Muscle'],
  },
  {
    name: 'Dumbbell Floor Press',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Dumbbells'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Overhead Press',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Dumbbells', 'Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Pike Press Holds',
    category: 'strength',
    focuses: ['Upper Body', 'Core'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['low', 'moderate'],
    goals: ['Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Band Rows',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bands'],
    intensity: ['Low', 'Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Backpack Rows',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Improve Fitness', 'Stay Consistent'],
  },
  {
    name: 'Seated Dumbbell Curls',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Dumbbells'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Build Muscle'],
  },
  {
    name: 'Bench or Chair Dips',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Dead Bug',
    category: 'core',
    focuses: ['Core', 'Full Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Improve Fitness', 'Stay Consistent', 'Increase Strength'],
  },
  {
    name: 'Bird Dog',
    category: 'core',
    focuses: ['Core', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness'],
  },
  {
    name: 'Front Plank',
    category: 'core',
    focuses: ['Core', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate', 'High'],
    impacts: ['low'],
    goals: ['Increase Strength', 'Improve Fitness', 'Stay Consistent'],
  },
  {
    name: 'Side Plank',
    category: 'core',
    focuses: ['Core'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate'],
    impacts: ['low'],
    goals: ['Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Hollow Hold',
    category: 'core',
    focuses: ['Core'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Mountain Climbers',
    category: 'conditioning',
    focuses: ['Core', 'Cardio', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate', 'high'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Jumping Jacks',
    category: 'conditioning',
    focuses: ['Cardio', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['moderate'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness', 'Stay Consistent'],
  },
  {
    name: 'Step Jacks',
    category: 'conditioning',
    focuses: ['Cardio', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Lose Weight', 'Stay Consistent', 'Improve Fitness'],
  },
  {
    name: 'High Knees',
    category: 'conditioning',
    focuses: ['Cardio', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate', 'high'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Marching in Place',
    category: 'conditioning',
    focuses: ['Cardio'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Low'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness'],
  },
  {
    name: 'Shadow Boxing',
    category: 'conditioning',
    focuses: ['Cardio', 'Full Body'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['low', 'moderate'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Brisk Walk',
    category: 'conditioning',
    focuses: ['Cardio'],
    environments: ['Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Lose Weight', 'Boost Endurance', 'Stay Consistent'],
  },
  {
    name: 'Jog Intervals',
    category: 'conditioning',
    focuses: ['Cardio'],
    environments: ['Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate', 'high'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Hill Walk Intervals',
    category: 'conditioning',
    focuses: ['Cardio', 'Lower Body'],
    environments: ['Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Boost Endurance', 'Lose Weight', 'Increase Strength'],
  },
  {
    name: 'Farmer Carry March',
    category: 'conditioning',
    focuses: ['Full Body', 'Core'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Dumbbells'],
    intensity: ['Moderate'],
    impacts: ['low'],
    goals: ['Increase Strength', 'Improve Fitness'],
  },
  {
    name: 'Band Pull-Aparts',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bands'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness', 'Build Muscle'],
  },
  {
    name: 'Lat Pulldown',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Leg Press',
    category: 'strength',
    focuses: ['Lower Body'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Seated Cable Row',
    category: 'strength',
    focuses: ['Upper Body'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Build Muscle', 'Increase Strength'],
  },
  {
    name: 'Bike Erg or Stationary Bike',
    category: 'conditioning',
    focuses: ['Cardio'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Low', 'Moderate', 'High'],
    impacts: ['low'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Rowing Machine',
    category: 'conditioning',
    focuses: ['Cardio', 'Full Body'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Moderate', 'High'],
    impacts: ['low'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Treadmill Incline Walk',
    category: 'conditioning',
    focuses: ['Cardio'],
    environments: ['Gym'],
    equipment: ['Full Gym'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Lose Weight', 'Boost Endurance', 'Stay Consistent'],
  },
  {
    name: 'Burpees',
    category: 'conditioning',
    focuses: ['Full Body', 'Cardio'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['High'],
    impacts: ['high'],
    goals: ['Lose Weight', 'Boost Endurance', 'Improve Fitness'],
  },
  {
    name: 'Bear Crawl',
    category: 'conditioning',
    focuses: ['Full Body', 'Core'],
    environments: ['Home', 'Gym', 'Outdoor'],
    equipment: ['Bodyweight'],
    intensity: ['Moderate', 'High'],
    impacts: ['moderate'],
    goals: ['Improve Fitness', 'Increase Strength'],
  },
  {
    name: 'Wall Sit',
    category: 'strength',
    focuses: ['Lower Body'],
    environments: ['Home', 'Gym'],
    equipment: ['Bodyweight'],
    intensity: ['Low', 'Moderate'],
    impacts: ['low'],
    goals: ['Stay Consistent', 'Improve Fitness', 'Increase Strength'],
  }
];
